name: Extract

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  extract_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run scripts
        run: |
          ./install.sh
          python extract_rainfall_with_coordinates.py

      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: rainfall_data
          path: |
            debug_rainfall_image.png
            rainfall_data_with_coordinates.csv
